### ISSUE TITLE
When installing plugin from repo, Gem has wrong name in Gemfile-plugins

### ISSUE THREAD

**Issue by garci66** [concerto-addons/concerto_manykinds#6]
The concerto-manykinds gem is added to the Gemfile-plugins as "concerto-manykinds" . Rake install fails when running since it can't find the gem, instead, we need to specify "concerto_manykinds" for it to work (replace dash with underscore).

**Comment by mfrederickson** [comment]
Octokit is used in concerto to get a dynamic list of addons for this organization, so the name of the repo should be changed to match the name of the gem and then it should appear properly in concerto.

**Comment by garci66** [comment]
Didnt konw. Thanks!

**Comment by mfrederickson** [comment]
I've renamed the repository to match the gem name and it tested ok.  Thanks for catching this.
